apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app-ingress  # Name of the Ingress
  annotations:
    kubernetes.io/ingress.class: nginx  # Specify the Ingress controller class (nginx)
    nginx.ingress.kubernetes.io/rewrite-target: /  # Rewrite the path to root ("/")
spec:
  rules:
    - http:
        paths:
          - path: /  # Path to match for the Ingress (root path)
            pathType: Prefix  # Type of path matching (prefix)
            backend:
              service:
                name: flask-app-service  # Name of your Flask app's Service
                port:
                  number: 5000  # Port your app listens on
